[project]
name = "MSUtils"
version = "0.1.2"
description = "Microstructure Utilities by Data Analytics in Engineering (DAE) group, University of Stuttgart"
authors = [{name = "Sanath Keshav", email = "keshav@mib.uni-stuttgart.de"}]

requires-python = ">=3.10,<3.15"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["MSUtils"]

[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-64", "osx-arm64"]

[tool.pixi.pypi-dependencies]
MSUtils = { path = ".", editable = true }

[tool.pixi.dependencies]
numpy = ">=2.5.3,<3"
h5py = ">=3.16.0,<4"
scipy = ">=1.18.1,<2"
scikit-image = ">=0.26.0,<0.27"
lxml = ">=6.1.3,<7"
sympy = ">=1.14.0,<2"
pyrecest = ">=2.2.2,<3"

matplotlib = ">=3.11.2,<4"
meshio = ">=5.3.5,<6"
plotly = ">=7.0.0,<8"

ipykernel = ">=7.3.0,<8"
nbformat = ">=5.11.1,<6"

pytest = ">=9.1.1,<10"
git = ">=2.55.0,<3"
pre-commit = ">=4.6.2,<5"
pyvista = ">=0.48.4,<0.49"
networkx = ">=3.6.1,<4"

[tool.pixi.feature.neper.dependencies]
neper = ">=5.0.0,<6"

[tool.pixi.environments]
default = {features = [], solve-group = "default"}
neper = {features = ["neper"], no-default-feature = true}

[project.scripts]
h52xdmf = "MSUtils.general.h52xdmf:main"
merge-h5 = "MSUtils.general.merge_h5_files:main"

[tool.pixi.tasks.h52xdmf]
args = ["file", { arg = "extra", default = "" }]
cmd  = "cd \"$INIT_CWD\" && python -m MSUtils.general.h52xdmf {{ extra }} {{ file }}"

[tool.pixi.tasks.make-video]
args = ["framerate", "name"]
cmd = '''cd "$INIT_CWD" && ffmpeg -framerate {{ framerate }} -i '{{ name }}.%04d.png' -vf "scale=trunc(iw/2)*2:trunc(ih/2)*2" -c:v libx264 -crf 18 -pix_fmt yuv420p '{{ name }}.mp4' '''
